name: Terraform check and plan

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main, develop]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo "Hello, world!"
